/**
 * Clinical Record Migrator
 *
 * Handles migration of historiaclinica (clinical records) to clinical_records table.
 * Covers Requirements 4.1 - 4.5, 2.6
 *
 * Key features:
 * - Maps historiaclinica fields to clinical_records with autogenerated id (no composite key preservation)
 * - Resolves idHistoriaClinica → patient_id via legacyIdToPatientId map
 * - Replaces <br> tags (and variants) with newlines in datos → notes
 * - Maps fechaConsulta → visit_date and assigns visit_fee from visitFeeByLegacyPatientId
 * - Supports idempotent re-execution via MigrationLogStore
 */

import { PoolClient } from 'pg';
import { PostgresClient, calculatePayloadHash } from '../db/client';
import { MigrationLogStore } from '../db/migration-log';

/**
 * Raw clinical record row from historiaclinica table dump
 * Requirement 4.1, 4.2, 4.3, 4.4
 */
export type ClinicalRecordRow = {
  idHistoriaClinica: number; // composite key in legacy; treated as patient reference (idFicha)
  idFicha: number; // patient_id legacy; resolve via legacyIdToPatientId
  fechaConsulta?: string; // 'YYYY-MM-DD' or '0000-00-00' (sentinel)
  datos?: string; // may contain <br> tags; replace with \n
};

/**
 * Result of clinical record migration
 */
export type ClinicalRecordMigrationResult = {
  /** Number of new clinical records inserted */
  migrated: number;
  /** Number of clinical records reused (already existed) */
  reused: number;
  /** Number of records excluded (patient not found in mapping) */
  excluded: number;
  /** Errors encountered (prevents row from being counted) */
  errors: Array<{ sourceId: number; error: string }>;
  /** Warnings (row processed but with some issue) */
  warnings: Array<{ sourceId: number; warning: string }>;
};

export type ClinicalRecordMigrator = {
  migrate(
    rows: ClinicalRecordRow[],
    legacyIdToPatientId: Map<number, number>,
    visitFeeByLegacyPatientId: Map<number, string>,
    client: PostgresClient,
    logStore: MigrationLogStore,
  ): Promise<ClinicalRecordMigrationResult>;
};

/**
 * Convert sentinel date ('0000-00-00') to null, or return the date as-is if valid
 * Requirement 4.4
 */
function normalizeDateField(dateStr?: string): string | null {
  if (!dateStr || dateStr === '' || dateStr === '0000-00-00') {
    return null;
  }
  return dateStr;
}

/**
 * Replace all variants of <br> tag with newline
 * Handles: <br>, <br/>, <BR>, <BR/>, and variants with spaces like < br >, < br/ >
 * Requirement 4.3
 */
function replaceBrTags(text?: string): string | null {
  if (!text) {
    return null;
  }

  // Regex to match <br> tag variants (case-insensitive, with optional spaces and optional forward slash)
  // Pattern: < * br *\/* *> (case-insensitive)
  const brRegex = /< *br *\/?  *>/gi;
  const result = text.replace(brRegex, '\n');

  return result;
}

/**
 * Parse visit fee from string value (retained from PatientMigrator)
 * Handles both string and numeric formats
 * Requirement 4.5
 */
function parseVisitFee(feeStr?: string): number | null {
  if (!feeStr || feeStr === '') {
    return null;
  }

  // Try to parse as number
  const parsed = parseFloat(feeStr);
  if (isNaN(parsed)) {
    return null;
  }

  return parsed;
}

/**
 * Create a ClinicalRecordMigrator instance
 */
export function createClinicalRecordMigrator(): ClinicalRecordMigrator {
  return {
    async migrate(
      rows: ClinicalRecordRow[],
      legacyIdToPatientId: Map<number, number>,
      visitFeeByLegacyPatientId: Map<number, string>,
      client: PostgresClient,
      logStore: MigrationLogStore,
    ): Promise<ClinicalRecordMigrationResult> {
      const result: ClinicalRecordMigrationResult = {
        migrated: 0,
        reused: 0,
        excluded: 0,
        errors: [],
        warnings: [],
      };

      if (rows.length === 0) {
        return result;
      }

      await client.withTransaction(async (tx: PoolClient) => {
        for (const row of rows) {
          try {
            const sourcePk = String(row.idHistoriaClinica);

            // Step 1: Check for idempotence
            // Requirement 9.1
            const existing = await logStore.findExisting(tx, 'historiaclinica', sourcePk);
            if (existing) {
              // Reuse existing clinical record
              result.reused++;
              continue;
            }

            // Step 2: Resolve patient (Requirement 4.2, 2.6)
            const patientId = legacyIdToPatientId.get(row.idFicha);
            if (!patientId) {
              // Patient not found in mapping → exclude row
              result.excluded++;
              result.errors.push({
                sourceId: row.idHistoriaClinica,
                error: `Patient ID ${row.idFicha} not found in mapping`,
              });
              continue;
            }

            // Step 3: Transform fields

            // Requirement 4.4: Map fechaConsulta → visit_date
            const visitDateValue = normalizeDateField(row.fechaConsulta);

            // Requirement 4.3: Replace <br> tags with newlines in datos
            const notesValue = replaceBrTags(row.datos);

            // Requirement 4.5: Assign visit_fee from visitFeeByLegacyPatientId
            const visitFeeStr = visitFeeByLegacyPatientId.get(row.idFicha);
            const visitFeeValue = parseVisitFee(visitFeeStr);

            // Step 4: Build INSERT values array
            const insertValues: unknown[] = [patientId, visitDateValue, notesValue, visitFeeValue];

            const columns = ['patient_id', 'visit_date', 'notes', 'visit_fee'];

            // Step 5: INSERT
            // Requirement 4.1: Generate autogenerated id (no composite key preservation)
            const insertResult = await client.query<{ id: number }>(
              tx,
              `INSERT INTO clinical_records (${columns.join(', ')}) VALUES (${columns
                .map((_, i) => `$${i + 1}`)
                .join(', ')}) RETURNING id`,
              insertValues,
            );

            const insertedId = insertResult[0]?.id;
            if (!insertedId) {
              throw new Error('INSERT did not return id');
            }

            // Step 6: Record in migration log
            const payloadHash = calculatePayloadHash(row);
            await logStore.record(tx, {
              sourceTable: 'historiaclinica',
              sourcePk,
              targetTable: 'clinical_records',
              targetId: insertedId,
              status: 'migrated',
              payloadHash,
              migratedAt: new Date(),
            });

            // Step 7: Update result
            result.migrated++;
          } catch (error) {
            result.errors.push({
              sourceId: row.idHistoriaClinica,
              error: String(error),
            });
          }
        }
      });

      return result;
    },
  };
}
